#############################################################################
# Makefile for building: libBlocks.so
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  Blocks.pro
# Template: app
# Command: C:\Qt\Qt5.2.1\5.2.1\android_armv7\bin\qmake.exe -spec android-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Blocks.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = C:\Users\Admi\necessitas\android-ndk-r6b/toolchains/arm-linux-androideabi-4.6.2/prebuilt/windows/bin/arm-linux-androideabi-gcc
CXX           = C:\Users\Admi\necessitas\android-ndk-r6b/toolchains/arm-linux-androideabi-4.6.2/prebuilt/windows/bin/arm-linux-androideabi-g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -g -gdwarf-2 -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -Wno-psabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfp -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums -DANDROID -Wa,--noexecstack -std=gnu++0x -g -g -gdwarf-2 -marm -O0 -fno-omit-frame-pointer -Wall -Wno-psabi -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\android-g++ -I. -Iqtquick2controlsapplicationviewer -I..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include -I..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQuick -I..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml -I..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets -I..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtSql -I..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtNetwork -I..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui -I..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore -I. -IC:\Users\Admi\necessitas\android-ndk-r6b/sources/cxx-stl/gnu-libstdc++/4.6.2/include -IC:\Users\Admi\necessitas\android-ndk-r6b/sources/cxx-stl/gnu-libstdc++/4.6.2/libs/armeabi-v7a/include -I..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include
LINK          = C:\Users\Admi\necessitas\android-ndk-r6b/toolchains/arm-linux-androideabi-4.6.2/prebuilt/windows/bin/arm-linux-androideabi-g++
LFLAGS        = --sysroot=C:\Users\Admi\necessitas\android-ndk-r6b/platforms/android-9/arch-arm/ -Wl,-soname,libBlocks.so -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) -LC:\Users\Admi\necessitas\android-ndk-r6b/sources/cxx-stl/gnu-libstdc++/4.6.2/libs/armeabi-v7a -LC:\Users\Admi\necessitas\android-ndk-r6b/platforms/android-9/arch-arm//usr/lib -LC:\Qt\Qt5.2.1\5.2.1\android_armv7\lib -lQt5Quick -Lc:\Utils\android\ndk/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Lc:\Utils\android\ndk/platforms/android-9/arch-arm//usr/lib -LC:\Utils\icu32_51_1_mingw48\lib -LC:\utils\postgresql\pgsql\lib -LC:\utils\mysql\mysql\lib -LC:\Utils\pgsql\lib -LC:\temp\opensll-android-master\openssl-android-master\lib -LC:\Qt\Qt5.2.1\5.2.1\android_armv7/lib -lQt5Qml -lQt5Widgets -lQt5Sql -lQt5Network -lQt5Gui -lQt5Core -lGLESv2 -lgnustl_shared -llog -lz -lm -ldl -lc -lgcc
AR            = C:\Users\Admi\necessitas\android-ndk-r6b/toolchains/arm-linux-androideabi-4.6.2/prebuilt/windows/bin/arm-linux-androideabi-ar cqs
RANLIB        = C:\Users\Admi\necessitas\android-ndk-r6b/toolchains/arm-linux-androideabi-4.6.2/prebuilt/windows/bin/arm-linux-androideabi-ranlib
QMAKE         = C:\Qt\Qt5.2.1\5.2.1\android_armv7\bin\qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = copy /y
SED           = $(QMAKE) -install sed
COPY_FILE     = cp -f
COPY_DIR      = xcopy /s /q /y /i
STRIP         = 
INSTALL_FILE  = copy /y
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = copy /y
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.cpp 
OBJECTS       = main.obj \
		qtquick2controlsapplicationviewer.obj
DIST          = ..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\spec_pre.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\shell-unix.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\unix.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\linux.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\gcc-base.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\gcc-base-unix.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\qdevice.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\device_config.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\shell-win32.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\qconfig.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_androidextras.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_declarative.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_declarative_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_script.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qt_functions.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qt_config.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\android-g++\qmake.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\spec_post.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\default_pre.prf \
		qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\resolve_config.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\default_post.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qml_debug.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\declarative_debug.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\android\android.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\android\android_deployment_settings.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\warn_on.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qt.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\resources.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\moc.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\unix\opengl.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\uic.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\unix\thread.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\testcase_targets.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\exceptions.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\yacc.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\lex.prf \
		Blocks.pro \
		Blocks.pro
QMAKE_TARGET  = libBlocks.so
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = libBlocks.so


first: all
####### Implicit rules

.SUFFIXES: .obj .c .cpp .cc .cxx

.cpp.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.obj:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.obj:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Blocks.pro ..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\android-g++\qmake.conf ..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\spec_pre.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\shell-unix.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\unix.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\linux.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\gcc-base.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\gcc-base-unix.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\qdevice.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\device_config.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\shell-win32.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\qconfig.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_androidextras.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_clucene_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_declarative.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_declarative_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_script.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_script_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qt_functions.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qt_config.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\android-g++\qmake.conf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\spec_post.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\default_pre.prf \
		qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.pri \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\resolve_config.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\default_post.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qml_debug.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\declarative_debug.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\android\android.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\android\android_deployment_settings.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\warn_on.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qt.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\resources.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\moc.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\unix\opengl.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\uic.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\unix\thread.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\testcase_targets.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\exceptions.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\yacc.prf \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\lex.prf \
		Blocks.pro \
		C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Quick.prl \
		C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Qml.prl \
		C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Network.prl \
		C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Core.prl \
		C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Gui.prl \
		C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Widgets.prl \
		C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Sql.prl
	$(QMAKE) -spec android-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Blocks.pro
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\spec_pre.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\shell-unix.conf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\unix.conf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\linux.conf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\gcc-base.conf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\gcc-base-unix.conf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\qdevice.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\device_config.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\common\shell-win32.conf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\qconfig.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_androidextras.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_androidextras_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_declarative.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_declarative_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_quick.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_script.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qt_functions.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qt_config.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\android-g++\qmake.conf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\spec_post.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\exclusive_builds.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\default_pre.prf:
qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.pri:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\resolve_config.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\default_post.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qml_debug.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\declarative_debug.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\android\android.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\android\android_deployment_settings.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\warn_on.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\qt.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\resources.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\moc.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\unix\opengl.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\uic.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\unix\thread.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\testcase_targets.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\exceptions.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\yacc.prf:
..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\mkspecs\features\lex.prf:
Blocks.pro:
C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Quick.prl:
C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Qml.prl:
C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Network.prl:
C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Core.prl:
C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Gui.prl:
C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Widgets.prl:
C:/Qt/Qt5.2.1/5.2.1/android_armv7/lib/libQt5Sql.prl:
qmake: FORCE
	@$(QMAKE) -spec android-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Blocks.pro

qmake_all: FORCE

dist: 
	@if not exist .tmp\libBlocks.so1.0.0 mkdir .tmp\libBlocks.so1.0.0 & if not exist .tmp\libBlocks.so1.0.0 exit 1
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp\libBlocks.so1.0.0\ && $(COPY_FILE) --parents qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.h .tmp\libBlocks.so1.0.0\ && $(COPY_FILE) --parents main.cpp qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.cpp .tmp\libBlocks.so1.0.0\ && (cd `dirname .tmp\libBlocks.so1.0.0` && $(TAR) libBlocks.so1.0.0.tar libBlocks.so1.0.0 && $(COMPRESS) libBlocks.so1.0.0.tar) && $(MOVE) `dirname .tmp\libBlocks.so1.0.0`\libBlocks.so1.0.0.tar.gz . && $(DEL_FILE) -r .tmp\libBlocks.so1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.obj: main.cpp qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\QApplication \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\qapplication.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcoreapplication.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qglobal.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qconfig.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qfeatures.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsystemdetection.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qprocessordetection.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcompilerdetection.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qglobalstatic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qbasicatomic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_bootstrap.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qgenericatomic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_msvc.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_integrity.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qoldbasicatomic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_vxworks.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_power.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_alpha.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_armv7.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_armv6.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_armv5.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_bfin.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_ia64.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_mips.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_s390.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_sh4a.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_sparc.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_x86.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_cxx11.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_gcc.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_unix.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qmutex.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qlogging.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qflags.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qtypeinfo.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qtypetraits.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsysinfo.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qstring.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qchar.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qbytearray.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qrefcount.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qnamespace.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qarraydata.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\string.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\cdefs.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\cdefs_elf.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\malloc.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\stdlib.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\alloca.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\strings.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\stdint.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\machine\_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\posix_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\stddef.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\compiler.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\asm\posix_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\asm\types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\machine\kernel.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\sysmacros.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\memory.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qstringbuilder.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qobject.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qobjectdefs.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qobjectdefs_impl.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qlist.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qalgorithms.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qiterator.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\limits.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\limits.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\limits.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\machine\internal_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\machine\limits.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\syslimits.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcoreevent.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qscopedpointer.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qmetatype.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qvarlengtharray.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcontainerfwd.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qisenum.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qobject_impl.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qeventloop.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qwindowdefs.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qwindowdefs_win.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qpoint.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsize.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qcursor.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\qdesktopwidget.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\qwidget.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qmargins.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qrect.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpaintdevice.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpalette.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qcolor.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qrgb.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qstringlist.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qdatastream.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qiodevice.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qpair.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qregexp.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qstringmatcher.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qbrush.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qvector.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qmatrix.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpolygon.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qregion.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qline.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qtransform.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpainterpath.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qimage.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpixmap.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsharedpointer.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qshareddata.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsharedpointer_impl.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qhash.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qfont.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qfontmetrics.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qfontinfo.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\qsizepolicy.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qkeysequence.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qevent.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qvariant.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qmap.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qdebug.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qtextstream.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qlocale.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\stdio.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qset.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcontiguouscache.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qurl.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qurlquery.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qfile.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qfiledevice.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qvector2d.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qtouchdevice.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qguiapplication.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qinputmethod.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\QGuiApplication
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.obj main.cpp

qtquick2controlsapplicationviewer.obj: qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.cpp qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\QApplication \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\qapplication.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcoreapplication.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qglobal.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qconfig.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qfeatures.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsystemdetection.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qprocessordetection.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcompilerdetection.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qglobalstatic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qbasicatomic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_bootstrap.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qgenericatomic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_msvc.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_integrity.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qoldbasicatomic.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_vxworks.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_power.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_alpha.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_armv7.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_armv6.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_armv5.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_bfin.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_ia64.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_mips.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_s390.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_sh4a.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_sparc.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_x86.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_cxx11.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_gcc.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qatomic_unix.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qmutex.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qlogging.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qflags.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qtypeinfo.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qtypetraits.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsysinfo.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qstring.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qchar.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qbytearray.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qrefcount.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qnamespace.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qarraydata.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\string.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\cdefs.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\cdefs_elf.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\malloc.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\stdlib.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\alloca.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\strings.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\stdint.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\machine\_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\posix_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\stddef.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\compiler.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\asm\posix_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\asm\types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\machine\kernel.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\sysmacros.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\memory.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qstringbuilder.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qobject.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qobjectdefs.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qobjectdefs_impl.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qlist.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qalgorithms.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qiterator.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\limits.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\limits.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\linux\limits.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\machine\internal_types.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\machine\limits.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\sys\syslimits.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcoreevent.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qscopedpointer.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qmetatype.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qvarlengtharray.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcontainerfwd.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qisenum.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qobject_impl.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qeventloop.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qwindowdefs.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qwindowdefs_win.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qpoint.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsize.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qcursor.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\qdesktopwidget.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\qwidget.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qmargins.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qrect.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpaintdevice.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpalette.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qcolor.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qrgb.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qstringlist.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qdatastream.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qiodevice.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qpair.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qregexp.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qstringmatcher.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qbrush.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qvector.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qmatrix.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpolygon.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qregion.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qline.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qtransform.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpainterpath.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qimage.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qpixmap.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsharedpointer.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qshareddata.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qsharedpointer_impl.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qhash.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qfont.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qfontmetrics.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qfontinfo.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtWidgets\qsizepolicy.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qkeysequence.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qevent.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qvariant.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qmap.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qdebug.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qtextstream.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qlocale.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\stdio.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qset.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qcontiguouscache.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qurl.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qurlquery.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qfile.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qfiledevice.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qvector2d.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qtouchdevice.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qguiapplication.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qinputmethod.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\QGuiApplication \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\QCoreApplication \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\QDir \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qdir.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qfileinfo.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\QQmlComponent \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qqmlcomponent.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qqml.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qqmlprivate.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qtqmlglobal.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qqmlparserstatus.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qqmlpropertyvaluesource.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qqmllist.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qmetaobject.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qqmlerror.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qjsvalue.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\QQmlEngine \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qqmlengine.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qjsengine.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQml\qqmldebug.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQuick\QQuickView \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQuick\qquickview.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQuick\qquickwindow.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtQuick\qtquickglobal.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qopengl.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\qt_windows.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\GLES2\gl2.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\GLES2\gl2platform.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\KHR\khrplatform.h \
		..\..\..\necessitas\android-ndk-r6b\platforms\android-9\arch-arm\usr\include\inttypes.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qopengles2ext.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qopenglext.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qwindow.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\QObject \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\QEvent \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\QMargins \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtCore\QRect \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qsurface.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qsurfaceformat.h \
		..\..\..\..\..\Qt\Qt5.2.1\5.2.1\android_armv7\include\QtGui\qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtquick2controlsapplicationviewer.obj qtquick2controlsapplicationviewer\qtquick2controlsapplicationviewer.cpp

####### Install

install_itemfolder_01: first FORCE
	@if not exist $(INSTALL_ROOT)\assets\qml mkdir $(INSTALL_ROOT)\assets\qml & if not exist $(INSTALL_ROOT)\assets\qml exit 1
	-$(INSTALL_DIR) C:\Users\Admi\Documents\GitHub\Blocks\qml\Blocks $(INSTALL_ROOT)\assets\qml\Blocks

uninstall_itemfolder_01: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)\assets\qml\Blocks
	-$(DEL_DIR) $(INSTALL_ROOT)\assets\qml 


install_target: first FORCE
	@if not exist $(INSTALL_ROOT)\libs\armeabi-v7a mkdir $(INSTALL_ROOT)\libs\armeabi-v7a & if not exist $(INSTALL_ROOT)\libs\armeabi-v7a exit 1
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)\libs\armeabi-v7a\$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)\libs\armeabi-v7a\$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)\libs\armeabi-v7a 


install:  install_itemfolder_01 install_target  FORCE

uninstall: uninstall_itemfolder_01 uninstall_target   FORCE

FORCE:

